language: ruby
rvm:
- 2.1.1
install:
- gem install jekyll
- gem install s3_website
- gem install compass
- gem install kramdown
script:
- jekyll build
- compass compile _sass
after_success:
- s3_website push --headless
- linkchecker http://suchow.io
env:
  global:
  - secure: m8oe6cKZaE0UFq1TinlaDzjY46k1NriyELbVtyJR3aoxAzw6lg0HyCcSyUf6kv1F2nNX+6R2MtVE/MpRCsYvbkif26ld+x1LUTStzpjKA+tlAnZax8okY4iMrE93jrwRlUNngFIyiLSifuPa1ZStpKkJMe/1qhp1AI/GiGeXyOg=
  - secure: sU5V97dBhnrxOLJjcZkRrc5upjk3SNG8dI57D78JAWJoepv9BXw3KBknyRs/MbGQjipvbEvP0ZeATLutfdkZnG/werJSQFpNaVRBmR9hfon2DSbQfEhteuOt9h4eo4iuyZT5lNu6LxUMGtySYz4ZpbkWu+c5x1VYlR0N4C/pFug=
  on:
    branch: master
