title:            Jordan Suchow
tagline:          Cognitive scientist.
description:      Jordan Suchow's portfolio of research and other work.
encoding:         utf-8
#Comment out url when working locally to resolve base urls correctly
url: https://suchow.io
enforce_ssl: suchow.io

# Owner/author information
owner:
  name:           Jordan Suchow
  avatar:         avatar.png
  bio:            "Cognitive scientist"
  email:          jwsuchow@gmail.com
  twitter:        suchow
  github:         suchow
  location:       "New York, NY"

# Links to include in top navigation
# For external links add external: true
links:
  - title: CV
    url: /cv.pdf

tools:
  standards:      "HTML, Jekyll, SCSS"
  software:       "Sublime Text, git"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
redirects:
  cv/index.html: https://suchow.io/assets/docs/suchow2020.pdf


timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "_drafts/**/*.pdf"]

gems:
  - jekyll-redirect-from
plugins:
  - jekyll-sitemap
  - jekyll-compass
